osx_image: xcode9.4
language: swift
script: fastlane scan
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
    - provider: script
        script: pod trunk push TinyKeychain.podspec
            on:
                repo: smolster/TinyKeychain
                branch: master
                tags: true
